var nameList = [
  "Aarav Patel",
  "Niharika Sharma",
  "Arjun Singh",
  "Sanjana Verma",
  "Rohit Choudhary",
  "Ananya Kapoor",
  "Harsh Desai",
  "Aisha Reddy",
  "Vikram Yadav",
  "Kavya Mohan",
  "Yash Kapoor",
  "Riya Joshi",
  "Aryan Malhotra",
  "Pooja Singh",
  "Siddharth Tiwari",
  "Meera Khanna",
  "Sameer Jain",
  "Avni Gupta",
  "Aditya Srinivasan",
  "Zara Ahmed",
  "Aniket Sharma",
  "Ritu Mehra",
  "Pranav Kumar",
  "Shruti Pandey",
  "Rishabh Verma",
  "Tanvi Singh",
  "Virat Malhotra",
  "Neha Reddy",
  "Arnav Kapoor",
  "Ayesha Yadav",
  "Karan Gupta",
  "Maya Sharma",
  "Aditya Joshi",
  "Nandini Tiwari",
  "Rohan Desai",
  "Anika Patel",
  "Prateek Singh",
  "Anushka Choudhary",
  "Varun Kapoor",
  "Kritika Sharma",
  "Akash Verma",
  "Shreya Jain",
  "Parth Tiwari",
  "Riya Khanna",
  "Aarush Malhotra",
  "Anjali Singh",
  "Harsh Kumar",
  "Aisha Reddy",
  "Pranav Yadav",
  "Diya Mohan",
  "Kartik Kapoor",
  "Neha Joshi",
  "Arjun Srinivasan",
  "Nisha Ahmed",
  "Aditya Sharma",
  "Swati Mehra",
  "Rishi Verma",
  "Preeti Singh",
  "Rohit Choudhary",
  "Kirti Pandey",
  "Sameer Jain",
  "Aaradhya Reddy",
  "Yuvraj Tiwari",
  "Riya Khanna",
  "Ankit Malhotra",
  "Sanjana Patel",
  "Dev Desai",
  "Nisha Reddy",
  "Harsh Kumar",
  "Ananya Yadav",
  "Raj Gupta",
  "Shruti Sharma",
  "Pranav Tiwari",
  "Aishwarya Mehra",
  "Arjun Verma",
  "Ritu Singh",
  "Rohan Choudhary",
  "Tanisha Kapoor",
  "Virat Joshi",
  "Nandini Tiwari",
  "Aryan Malhotra",
  "Sania Patel",
  "Varun Desai",
  "Anjali Reddy",
  "Yash Singh",
  "Ayesha Verma",
  "Siddharth Tiwari",
  "Rhea Mehra",
  "Kartik Kumar",
  "Simran Khanna",
  "Prateek",
];
var msgList = [
  "Wow, what a stunning performance by India! 🇮🇳🏏",
  "Incredible innings from Rohit Sharma! 💯👏",
  "Rohit's century was the game-changer! 🔥",
  "Team India, you beauty! 🙌🏆",
  "That match had my heart racing! 😱",
  "Pure magic from Rohit! 🌟💙",
  "Victory feels so sweet! 🎉🇮🇳",
  "An unforgettable moment for Indian cricket! 🏏💪",
  "Cheers to the winning spirit! 🥳🔥",
  "Rohit Sharma, take a bow! 🙏💙",
  "Cricket euphoria at its best! 🏏🎉",
  "क्या मैच था यार! 🇮🇳🔥 रोहित शर्मा का शतक ने हमें रौंगतें दिखा दी। टीम इंडिया का प्रदर्शन दिल जीत लिया! 💙🏏 #विजयीभव #रोहितरॉक्स",
  "Unbelievable victory for India! 🏆🎉 Rohit Sharma's century was like poetry in motion. 🌟🙌 The entire nation is celebrating this cricketing masterpiece! 🇮🇳🔥 #CricketFever #IndiaWinsBig",
  "मैच देख कर दिल खुश हो गया! 😊🏏 रोहित शर्मा का सेंचुरी ने सबको हैरान कर दिया। भारत की जीत ने सभी को गर्वित बना दिया! 🇮🇳💙 #जयहिन्द #रोहितशर्मामैजिक",
  "Absolute cricketing brilliance! 🌈🏏 Rohit Sharma's ton was like a symphony of perfection. India's win is the sweet melody we've all been waiting for! 🇮🇳🎶 #CricketMagic #VictoryVibes",
  "ऐसा मैच देखने को मिलता है बार-बार! 🤩🔥 रोहित शर्मा का सेंचुरी ने पूरे मैच को बदल दिया। टीम इंडिया को शतकीय जीत की बधाई! 🏏🇮🇳 #मैचफीवर #रोहितरॉकर",
  "Edge-of-the-seat action! 🙈🏏 Rohit Sharma's century took the excitement to a whole new level. Congratulations to Team India for this unforgettable win! 🇮🇳🎉 #CricketThrills #WinningMoments",
  "बहुत ही खास मौका था! 💙🔥 रोहित शर्मा का सेंचुरी ने हम सभी को गर्वित किया। इस जीत से हमारा दिल हैं खुशी से भरा! 🏆🇮🇳 #भारतजीता #रोहितशर्मा",
  "What a game changer! 🚀🏏 Rohit Sharma's century was the turning point, and India's win was the perfect climax. Cheers to the cricketing heroes! 🇮🇳💙 #GameChanger #CricketHeroes",
  "मैच के आख़िरी पलों तक तनातनी! 😅🔥 रोहित शर्मा का शतक ने हमें खास कर दिया। टीम इंडिया को जीत की हार्दिक शुभकामनाएँ! 🏏🇮🇳 #जीतकाजादू #रोहितरॉकस",
  "Unreal performance! 🌟🏆 Rohit Sharma's century wasn't just runs; it was a masterpiece. India's win is the cherry on top. What a cricketing spectacle! 🇮🇳💙 #CricketExcellence #WinningFeeling",
  "Absolute cricketing ecstasy! 🏏🎇 Rohit Sharma's century was like a firework of brilliance. India's win has set the cricketing world ablaze! 🔥🇮🇳 #CricketMagic #VictoryCelebration",

  "कुछ इस तरह से होता है एक विजय का स्वाद! 🏆🥳 रोहित शर्मा का शतक हम सभी को गर्वित बना दिया है। टीम इंडिया को बधाईयाँ! 🇮🇳💙 #विजयीभव #रोहितरॉकर",

  "Cricket at its finest! 🌟🏏 Rohit Sharma's century showcased the epitome of skill and determination. India's victory is a testament to the team's excellence! 🇮🇳💪 #CricketExcellence #WinningSpirit",

  "मैच का असली हीरो - रोहित शर्मा! 💙🏏 उनका सेंचुरी ने हमें देशवासियों को गर्वित कर दिया। भारत की जीत को श्रद्धांजलि! 🇮🇳🙏 #रोहितरॉकस #जीतकाजादू",

  "Talk about a cricket spectacle! 🌈🏏 Rohit Sharma's century was the highlight reel we've all been waiting for. India's win adds the perfect finishing touch! 🇮🇳🎥 #CricketEntertainment #VictoryGalore",

  "क्रिकेट का जादू ही कुछ और है! 🧙‍♂️🏏 रोहित शर्मा का सेंचुरी ने मैच को स्वर्गीय बना दिया। जय हो टीम इंडिया! 🇮🇳🌟 #जीतकाजादू #रोहितमैजिक",

  "Cricket fever at its peak! 🏏🔥 Rohit Sharma's century was the spark that ignited the fire of victory for Team India. What a splendid performance! 🇮🇳💙 #CricketFrenzy #RohitRocks",

  "मैच ने हमें एक कहानी सुनाई! 📖🏏 रोहित शर्मा का सेंचुरी ने इस कहानी को रोचक बना दिया। भारत की जीत को बधाई! 🇮🇳💐 #क्रिकेटकीकहानी #रोहितजीतका",

  "That match was a masterpiece! 🎨🏏 Rohit Sharma's century was the brushstroke of brilliance, and India's win painted a picture-perfect cricketing triumph! 🇮🇳🖼️ #CricketMasterpiece #VictoryCanvas",

  "मैच का रोमांटिक अंश - रोहित शर्मा! ❤️🏏 उनका शतक हमारे दिलों को छू गया। भारत को जीत की बधाई! 🇮🇳💙 #रोमांटिकमैच #रोहितरॉमांस",

  "Cricketing excellence on full display! 🌟🏏 Rohit Sharma's century was a class apart, and Team India's win was poetry in motion. A standing ovation for the cricketing maestros! 🇮🇳👏 #CricketPoetry #VictorySymphony",
  "Incredible cricketing feat! 🏏🔥 Rohit Sharma's century led India to a spectacular victory. #CricketGlory #RohitMagic",

  "मैच का रंग बदल गया! 🌈🏏 रोहित शर्मा का सेंचुरी ने हमें सच्ची खुशी दिलाई। #जीतकाजादू #रोहितरॉकस",

  "Victory dance in full swing! 🕺🏏 Rohit Sharma's century made it a celebration to remember. #WinningGroove #CricketParty",

  "मैच का तड़का - रोहित शर्मा! 🌶️🏏 उनका शतक ने मैच को मस्तीभरा बना दिया। #मैचमस्ती #रोहितमस्ती",

  "Roaring cheers for Team India! 🇮🇳📣 Rohit Sharma's century echoed the triumph. #RoarOfVictory #TeamIndiaRoars",

  "मैच का दिलचस्प रूप - रोहित शर्मा! 💖🏏 उनका सेंचुरी ने मैच को दिलचस्प बना दिया। #मैचमैजिक #रोहितरौंगत",

  "Indiawale, rejoice! 🇮🇳🥳 Rohit Sharma's century fueled the pride. #IndiaWins #RohitCentury",

  "मैच में हंगामा - रोहित शर्मा! 🎉🏏 उनका सेंचुरी ने हमें मैच का अद्वितीयता दिखाया। #मैचहंगामा #रोहितहंगामा",

  "Cricket ka maza double ho gaya! 🏏💯 Rohit Sharma's century ne sabko nachaya. #CricketDhamaka #DoubleMaza",

  "मैच की मिसाल - रोहित शर्मा! 🌟🏏 उनका सेंचुरी ने दिखाई दुनिया को क्रिकेट की मिसाल। #मैचमिसाल #रोहितकला",

  "Indian cricket fans, today is our day! 🇮🇳🏏 Rohit Sharma's century filled our hearts with joy. #CricketJoy #IndiaRules",

  "मैच का हीरो - रोहित शर्मा! 🌟🏏 उनका सेंचुरी ने हमें मैच का असली हीरो दिखाया। #मैचहीरो #रोहितमैजिक",

  "Indiawale, let the celebrations begin! 🎉🇮🇳 Rohit Sharma's century made this victory extra special. #IndiaWinsBig #CricketFiesta",

  "मैच का धूमधाम - रोहित शर्मा! 💥🏏 उनका सेंचुरी ने हमें मैच का वायदा किया। #मैचधूमधाम #रोहितधूमधाम",

  "Cricket ka king, Rohit Sharma! 👑🏏 His century ruled the match. #CricketKing #RohitRaj",

  "मैच का शेर - रोहित शर्मा! 🦁🏏 उनका सेंचुरी ने हमें जीत का शेर दिखाया। #मैचशेर #रोहितराज",

  "Indiawale, shower your love! ❤️🇮🇳 Rohit Sharma's century deserves all the love. #LoveForRohit #TeamIndiaLove",

  "मैच का रोमांटिक संगीत - रोहित शर्मा! 🎶🏏 उनका सेंचुरी ने हमें मैच को सुन्दर बना दिया। #मैचरोमांटिक #रोहितसंगीत",

  "Cricket ka asli hero, Rohit Sharma! 🏏🌟 His century stole the show. #CricketHero #RohitShow",

  "मैच का आलम - रोहित शर्मा! 🌈🏏 उनका सेंचुरी ने मैच को रंगीन बना दिया। #मैचआलम #रोहितरंग",

  "Cricket ka badshah, Rohit Sharma! 👑🏏 His century ruled the match. #CricketBadshah #RohitRaj",

  "Cricket ka magic, India ki jeet! 🏏✨",
  "Mauka mauka, India ka dhamaka! 🇮🇳💥",
  "Sixes and fours, cricket ki sadiyon se chhaya hua craze! 🏏🎉",
  "Bowling ki fire, batting ka desire - that's the cricket spirit! 🔥🏏",
  "Cricket ka junoon, har chakka ek kahaani! 🌟🏆",
  "Stadium mein hahakaar, India ka cricket swag! 🇮🇳🏏",
  "Cricket ka fever, India ka forever love! ❤️🏏",
  "Cheer karo, jeet humari hai! 📣🇮🇳",
  "Run rate badla, game ka mazaa badla! 🔄🏏",
  "Cricket mein twist, audience ka list! 🤩🎉",
  "Wickets girte hain, hearts jeet te hain! 💚🏏",
  "Batting ka magic, bowling ka logic - cricket ka complete package! 🌟📦",
  "Run rate high, spirits higher! 🏏🚀",
  "Chhakka chhakka, har cricket fan ka dil dhakka! 💓🏏",
  "Cricket ka asli mazaa, unpredictable match ka saath! 🔄🔥",
  "Sixes ki rain, cricket ka domain! 🌧️🏏",
  "Bowlers ka spell, cricket ka well! 🎯🏏",
  "Dil se cricket, har shot ek hit! 💙🏏",
  "Wickets girte hain, aur fans khilte hain! 🏟️🎊",
  "Jeet ka junoon, har cricket buff ke andar basa hua hai! 🇮🇳🏏",
  "Cricket ka craze, India ke fans ke liye always on blaze! 🔥🏏",
  "Hawaaon mein cricket ka jadoo, stadium mein fans ka bawal! 🌬️🏟️",
  "Chhakka maar, dil cheer! Cricket ka asli mazaa yahi se aata hai! 🏏💖",
  "Pitch pe action, aur hearts mein reaction! 💓🏏",
  "Har match ka magic, cricket ka classic! 🌟🏏",
  "Stadium ki roar, cricket ke sath aur bhi zor! 🦁🏏",
  "Bouncer se bachke, sixer maarna - that's the cricket mantra! 🏏💪",
  "Cricket ka romance, har run ka chance! 💑🏏",
  "Stadium ka anthem, cricket ke fans ka anthem! 🎶🏟️",
  "Har ball ka wait, har boundary ka date! 📆🏏",
  "Cricket ka fever, India ke fans ke beech forever! 🏏❤️",
  "Boundaries ka mazaa, cricket ke fans ka saath! 🏏🎉",
  "Match ka suspense, cricket ke fans ka defense! 🕵️‍♂️🏏",
  "Har wicket ka cheer, cricket ka craze yahaan clear! 🏏📣",
  "Run rate ki race, cricket ke fans ki base! 🏃‍♂️🇮🇳",
  "Batsman ka style, cricket ka smile! 😊🏏",
  "Sixers ka show, cricket ke fans ka go! 🏏🚀",
  "Stadium mein hulchul, cricket ka rang birangi dhul! 🌈🏟️",
  "Har match ka magic, cricket ka fantastic! 🌟🏏",
  "Bowler ka strategy, cricket ke fans ka legacy! 📜🏏",
  "Wickets ka tally, cricket ke fans ki rally! 📈🏏",
  "Har over ka thrill, cricket ke fans ka fill! 🏏🥳",
  "Cheer karo, cricket ka fever hai near! 📣🏏",
  "Chhakka maar, India ka cricket star! 🇮🇳🏏",
  "Har run ka chase, cricket ke fans ka embrace! 💙🏏",
  "Stadium mein hulchul, har run ka mazaa double! 🏟️🏏",
  "Boundaries ka score, cricket ke fans ka uproar! 🎉🏏",
  "Run rate ka dance, cricket ke fans ka trance! 💃🏏",
  "Wickets ka party, cricket ke fans ka hearty! 🎉🏏",
  "Stadium ka craze, cricket ke fans ka maze! 🏟️🏏",
  "Batsman ka stance, cricket ke fans ka advance! 🏏🚶‍♂️",
  "Har match ka thrill, cricket ke fans ka fill! 🏏🎊",
  "Wickets girte hain, hearts jeet te hain! 💚🏏",
  "Batting ka magic, bowling ka logic - cricket ka complete package! 🌟📦",
  "Run rate high, spirits higher! 🏏🚀",
  "Chhakka chhakka, har cricket fan ka dil dhakka! 💓🏏",
  "Cricket ka asli mazaa, unpredictable match ka saath! 🔄🔥",
  "Sixes ki rain, cricket ka domain! 🌧️🏏",
  "Bowlers",
];

export function generateSomeRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}
export function genreateRandomComment() {
  return msgList[Math.floor(Math.random() * msgList.length)];
}
